DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
  "id" SERIAL PRIMARY KEY NOT NULL,
  "first_name" VARCHAR(255) NOT NULL,
  "last_name" VARCHAR(255) NOT NULL,
  "email" VARCHAR(255) NOT NULL,
  "password" VARCHAR(255) NOT NULL,
  "role" VARCHAR(255) DEFAULT "user" NOT NULL,
  "proof" VARCHAR(255) NOT NULL
);
